import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SideMenu } from "@/components/SideMenu";
import MainMenu from "@/components/MainMenu";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Huraira Photos Cloud",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <MainMenu />

        <div className="flex">
          <SideMenu />

          <div className="w-full px-4 pt-8">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
